<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends EntityRepository
{
    public function sortInvites()
    {
        $query = $this->_em->createQuery(
            "SELECT i FROM AppBundle:Invitation i ORDER BY i.id ASC");

        return $query->getResult();
    }
}
