<?php

namespace AppBundle\Repository;

/**
 * ToDoListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToDoListRepository extends \Doctrine\ORM\EntityRepository
{
}
