<?php

namespace AppBundle\Repository;

/**
 * TravelInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
