<?php

namespace AppBundle\Repository;

/**
 * WeddingInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeddingInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
