security:

    providers:
        in_memory:
            memory:
              users:
                ewa:
                    password: $2y$12$ngx3PT5LWTqSpgtQ0YOp2e82AjngpZ5l6O8XgTk8LNtZrQtbBpA/u
                    roles: 'ROLE_USER'

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~


    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        - { path: ^/admin, roles: ROLE_USER }